### PR TITLE
Create RectangleOverlap.java

### PR DESCRIPTION
**Pull request by ShantiMow**

### CODE REVIEW

**Comment by himanshukharkar** [comment]
can you add leetcode challenge link ?

**Comment by ShantiMow** [comment]
@himanshukharkar [https://leetcode.com/problems/rectangle-overlap/](url)

**Comment by himanshukharkar** [comment]
@ShantiMow seems like your code is invalid

image

**Comment by ShantiMow** [comment]
@himanshukharkar Do Check the code now and It is in JAVA .

**Pull request merged**
