### PR TITLE
Create WaterAndJugProblem.java

### PR DESCRIPTION
**Pull request by ShantiMow**

### CODE REVIEW

**Comment by himanshukharkar** [comment]
can you add leetcode challenge link ?

**Comment by ShantiMow** [comment]
@himanshukharkar [https://leetcode.com/problems/water-and-jug-problem/](url)

**Comment by himanshukharkar** [comment]
@ShantiMow kindly make sure your code is accepted on leetcode and passes test 

image

**Comment by ShantiMow** [comment]
@himanshukharkar Do run the now and change the language to java.

**Pull request merged**
