### PR TITLE
remove element (problem 27) python program added

### PR DESCRIPTION
**Pull request by codewithMauny**
https://leetcode.com/problems/remove-element/description/

### CODE REVIEW

**Comment by Ayushd70** [comment]
please attach a screenshot of the accepted code.

**Comment by codewithMauny** [comment]
> please attach a screenshot of the accepted code.

accepted

**Comment by Ayushd70** [comment]
> > please attach a screenshot of the accepted code.
> 
> accepted

add the problem link in commit message.

**Comment by codewithMauny** [comment]
https://leetcode.com/problems/remove-element/description/

**Pull request merged**
