### PR TITLE
Merging two Binary Trees in Java

### PR DESCRIPTION
**Pull request by AnirudhPanda**
Challenge link: https://leetcode.com/problems/merge-two-binary-trees/
img: 
Screenshot (65)

### CODE REVIEW

**Comment by Ayushd70** [comment]
attach the  screenshot of accepted code  and add challenge link in the commit message.

**Comment by AnirudhPanda** [comment]
DONE @Ayushd70

**Comment by Ayushd70** [comment]
> DONE @Ayushd70

can you post the full screenshot?

**Comment by AnirudhPanda** [comment]
> > DONE @Ayushd70
> 
> can you post the full screenshot?

Screenshot (66)

**Pull request merged**
